version: "3"

server:
  command: "php artisan octane:roadrunner"
#  command: "php grpc-worker.php"

grpc:
  listen: "tcp://0.0.0.0:9001"
  proto:
    - "proto/helloworld.proto"

http:
  address: 0.0.0.0:9001

# Опции для настройки worker'ов
workers:
  command: "php worker.php"  # Укажите команду для запуска worker'ов
  relay: "pipes"              # Используйте pipes для передачи данных между сервером и worker'ами
  pool:
    num: 10                    # Количество worker'ов
    max: 20                   # Максимальное количество worker'ов
